spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    #driver-class-name: org.h2.Driver
    #username: task
    #password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
